// import { createElement } from 'lwc';
import { createElement } from "@lwc/engine-dom";
import CaseActivityLog from "c/caseActivityLog";

describe("c-case-activity-log", () => {
  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Arrange
    const element = createElement("c-case-activity-log", {
      is: CaseActivityLog
    });

    // Act
    document.body.appendChild(element);

    // Assert
    // const div = element.shadowRoot.querySelector('div');
    expect(1).toBe(1);
  });
});
